# Generated by Django 4.2.4 on 2023-08-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='1', upload_to='advertisement/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
